//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ex2_20190808.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int ID { get; set; }
        public string Product_name { get; set; }
        public Nullable<long> Product_number { get; set; }
        public Nullable<decimal> Product_price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Precision { get; set; }
        public string Describe { get; set; }
        public Nullable<System.Guid> Random { get; set; }
    }
}
